-- apply changes
create table buyer_entity (
  id                            bigint generated by default as identity not null,
  name                          varchar(100) not null,
  constraint pk_buyer_entity primary key (id)
);

