ebean:
  db:
    ddl:
      run: true
      generate: true
#  platform: ebean-postgres
#  dbSchema: ${db.name:mydb}
#  migration.run: true
datasource:
  db:
    username: ${db.username:sa}
    password: ${db.password:}
    databaseUrl: ${db.url:jdbc:h2:mem:app}
    databaseDriver: ${db.driver:org.h2.Driver}